apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cost-dashboard
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cost-dashboard
  template:
    metadata:
      labels:
        app: aws-cost-dashboard
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3001